# frozen_string_literal: true

source "https://rubygems.org"


# gem "rails"
gem 'cucumber', '5.2'
gem 'capybara', '3.33'
gem 'selenium-webdriver', '3.142.7'
gem 'rspec', '3.10'
gem 'faker', '2.18'
gem 'bson', '4.12'
gem 'mongo', '2.14.0'